### ISSUE TITLE
[FEATURE] Enhancement to itsmyconfig config command

### ISSUE THREAD

**Issue by Zarkness** [itsme-to/ItsMyConfig#12]
**Is your request related to a problem? Please describe it **.
The command /itsmyconfig config <placeholder> <new content> is only for the config.yml file and also deletes the previous content of the placeholder.

**Describe the solution you would like**
the solution would be to add that you can edit the value of the placeholders in any .yml file.

Add as you have the ItsMyMeta plugin add that the command can edit the value of the placeholder by user, besides adding to edit it globally for all users where you keep both the value that you put by default in the . yml as the one that has the user, to use the value that has each user that is %itsmyconfig_<placeholder>_uservalue% and if it is %itsmyconfig_<placeholder>% and you edited the value globally that shows the new value. apart from adding a new command that would be /itsmyconfig reset <argument -g or -u> <placeholder> (-g => global and -u => user, if you use -u will ask for the user, this would be for both the reset and the config).

**Comment by itsme-to** [comment]
Fixed !
