### ISSUE TITLE
[FEATURE] New Placeholder type

### ISSUE THREAD

**Issue by Zarkness** [itsme-to/ItsMyConfig#13]
creating a new type of placeholder that would be the same that has the ItsMyMeta team which would need to have support for different team plugins where you could create a placeholder with a value for each team, plugins that I can think of to support this type of placeholder, bentobox, lands, would be the utility in the ItsMyMeta and replicate it in this plugin.

**Comment by itsme-to** [comment]
Hello, unfortunately, that is not the goal of ItsMyConfig. We do not save any data.
