### ISSUE TITLE
[FEATURE] Add support for PacketEvents

### ISSUE THREAD

**Issue by NoltoxGit** [itsme-to/ItsMyConfig#14]
Hello,
Is it possible to add PacketEvents support instead of ProtocolLib?

There are already several other plugins that have added PacketEvents support, or even replaced ProtocolLib to use PacketEvents only.

For all the developers who have switched, this one is better, and the code is better maintained by the developer and the community. :)

## GitHub link: https://github.com/retrooper/packetevents

**Comment by iiAhmedYT** [comment]
Well. I wouldn't put it as "planned" yet, however, maybe in the future when the plugin is in the most stable state
