### ISSUE TITLE
[BUG] Font placeholder don't support anymore placeholder

### ISSUE THREAD

**Issue by itsme-to** [itsme-to/ItsMyConfig#8]
**Describe the bug**
When you have a {placeholder} inside a font placeholder (tested smallCaps) the placeholder is not parse

**To Reproduce**
1. Run the command `/papi parse me %itsmyconfig_font_smallCaps_{itsmyconfig_store}%`

**Expected behavior**
Parce the placeholder inside

**Screenshots**
![CleanShot 2024-05-13 at 13 59 57](https://github.com/itsme-to/ItsMyConfig/assets/43671109/8f359c8f-38f2-40fe-b7c4-a41243508337)

**Software (please complete the following information):**
 - Spigot: Paper
 - Version: 1.20.1

**Comment by na2sime** [comment]
I updated the code to make it work.

Let me know if you have new issues.
